.TH XFPM-POWER-BACKLIGHT-HELPER "1" "August 2013" "xfpm-power-backlight-helper" "User Commands"
.SH NAME
xfpm-power-backlight-helper \- control the brightness from the command line
.SH DESCRIPTION
.SS "Usage:"
.IP
xfpm\-power\-backlight\-helper [OPTION...]
.PP
XFCE Power Manager Backlight Helper
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.SS "Application Options:"
.TP
\fB\-\-set\-brightness\fR
Set the current brightness
.TP
\fB\-\-get\-brightness\fR
Get the current brightness
.TP
\fB\-\-get\-max\-brightness\fR
Get the number of brightness levels supported
.SH "SEE ALSO"
.IX Header "SEE ALSO"
\&\fIxfce4-power-manager\fR\|(7)
.PP
This program is a part of xfce4-power-manager.